### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by rupali-codes** [pratikbutani/pratikbutani#1]
Hi, your readme looks great especiallly the gif, But there's a small spelling error

![image](https://user-images.githubusercontent.com/78981177/197166413-e634b6c5-ff56-44c8-9b83-e4a0b29ced3d.png)

Kindly update this (snack to snake) :D

**Comment by pratikbutani** [comment]
Haha 😂 Cool will check it out. Thank you so much 👍
